using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCService
{
    /// <summary>
    ///     Hospital entity, contains: id (int - autogenerated), name (string), address (string), 
    ///     licenseNmb (string)
    /// </summary>
    class Hospital
    {
        private static int count = 1;
        private string name;
        private int id;
        private string licenseNmb;
        private string address;
        /// <summary>
        ///     parameter constructor
        /// </summary>
        /// <param name="name"></param>
        /// <param name="licenseNmb"></param>
        /// <param name="address"></param>
        public Hospital(string name, string licenseNmb, string address)
        {
            this.id = count;
            count++;
            this.name = name;
            this.licenseNmb = licenseNmb;
            this.address = address;
        }
        /// <summary>
        ///     return a formatted string which contain the hospital's information
        /// </summary>
        /// <returns></returns>
        override public string ToString()
        {
            return string.Format("{0, -3} | {1,-22} | {2,-7} | {3,-20}", id.ToString("000"), name, licenseNmb, address);
        }
        /// <summary>
        ///     properties
        /// </summary>
        public int ID
        {
            get { return id; }
        }
        public string Name
        {
            get { return name; }
            set { name = value; }
        }
        public string LicenseNmb
        {
            get { return licenseNmb; }
            set { licenseNmb = value; }
        }
        public string Address
        {
            get { return address; }
            set { address = value; }
        }
    }
}
