using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCService
{
    /// <summary>
    ///     Patient entity, contains: id (int - autogenerated), name (string), gender (string), 
    ///     dob (DateTime), address (string)
    /// </summary>
    class Patient
    {
        private static int count = 1;
        private string name;
        private string gender;
        private DateTime dob;
        private int id;
        private string address;
        /// <summary>
        ///     parameter constructor
        /// </summary>
        /// <param name="name"></param>
        /// <param name="gender"></param>
        /// <param name="dob"></param>
        /// <param name="address"></param>
        public Patient(string name, string gender, DateTime dob, string address)
        {
            this.id = count;
            count++;
            this.name = name;
            this.gender = gender;
            this.dob = dob;
            this.address = address;
        }
        /// <summary>
        ///     return a formatted string which contains patient's information
        /// </summary>
        /// <returns></returns>
        override public String ToString()
        {
            string format = "MMM dd yyyy";
            return string.Format("{0, -3} | {1,-14} | {2,-7} | {3,-10} | {4,-20}", id.ToString("000"), name, gender.ToUpper(), dob.ToString(format), address);
        }
        /// <summary>
        ///     properties
        /// </summary>
        public int ID
        {
            get { return id; }
        }
        public string Name
        {
            get { return name; }
            set { name = value; }
        }
        public string Gender
        {
            get { return gender; }
            set { gender = value; }
        }
        public DateTime DOB
        {
            get { return dob; }
            set { dob = value; }
        }
        public string Address
        {
            get { return address; }
            set { address = value; }
        }
    }
}
